### ISSUE TITLE
Does not work with latest clusterctl

### ISSUE THREAD

**Issue by rhtyd** [kubernetes-sigs/cluster-api-provider-digitalocean#270]
I get this:
```
clusterctl init --infrastructure digitalocean
Fetching providers
Error: current version of clusterctl is only compatible with v1alpha4 providers, detected v1alpha3 for provider infrastructure-digitalocean
```

**Comment by timoreimann** [comment]
I think the issue is that, despite [having v1alpha4 configured in our master metadata.json](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/6e448e125f44c08c614f36fce51f9aab5ba895ac/metadata.yaml#L9), it is not part of our [latest v0.4.3 release](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/v0.4.3/metadata.yaml).

@cpanato @prksu do we need another release to address the issue?

**Comment by cpanato** [comment]
i will take a look, but we will need a new release for sure.
but first let me sync with the latest CAPI and then we can cut a release. WDYT?

**Comment by cpanato** [comment]
we need a v1alpha4 release, will make the things to make this happen

**Comment by cpanato** [comment]
can you try again?
we made a v1alpha4 release https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/releases/tag/v0.5.0

**Comment by hwinkel** [comment]
I think v1beta1 is out now as well. may the README.md should be updated too ?

**Comment by rhtyd** [comment]
Thanks closing this now, will try the new one.
